### ISSUE TITLE
Collapse instead of closing

### ISSUE THREAD

**Issue by lyucean** [jmerle/inkdrop-tray#17] opened 2023-03-05 01:23 UTC
**Hi my friend, thanks for the great plugin!**

It would be great if by clicking on the Exit icon (in the right corner), the program would also be minimized to tray. You can put it in the settings if it's not convenient for everyone. Thank you :)

**Comment by jmerle** [comment] 2023-05-23 01:31
Whoops, completely forgot about this issue until I saw you forked the repository. This is a duplicate of #14, which was closed because the feature is impossible to implement in an Inkdrop plugin. I just tried the [attempted implementations from a year ago](https://forum.inkdrop.app/t/detect-and-cancel-inkdrop-exiting-from-plugin/3233) again and the behavior is still the same, so I'm closing this issue.

**Closed as completed by jmerle** 2023-05-23 01:31 UTC

**Comment by lyucean** [comment] 2023-05-23 10:01
Yes, I also tried yesterday, then I came across your same [message](https://forum.inkdrop.app/t/detect-and-cancel-inkdrop-exiting-from-plugin/3233) 😂

**Comment by lyucean** [comment] 2023-05-23 10:01
Thanks for the plugin. Actually, I liked the idea of ​​adding a minimize/maximize tray hotkey. But until the hands got to it. I'll do it a bit later. May I suggest a PR to your repository?

**Comment by jmerle** [comment] 2023-05-28 21:57
I don't think you need a plugin for that, the `application:toggle-main-window` command already does that. I've got it bound to <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>E</kbd> since I started using Inkdrop, this is my keymap file (Preferences > Keybindings > your keymap file):
```cson
'global':
  'ctrl-alt-E': 'application:toggle-main-window'
```

**Comment by lyucean** [comment] 2023-05-29 20:55
Thanks a lot, I did it!
